### ISSUE TITLE
Installation issues/instructions

### ISSUE THREAD

**Issue by robot-army** [OpenModelica/OMSysIdent#6]
Hi, 

I'm moving over from OpenModelica on Windows in order to get OMSysIdent working under linux. 

I've just installed a brand new copy of Ubuntu 21.04, and OpenModelica using the instructions here: 
https://openmodelica.org/download/download-linux 
(including the step to install all the libraries).

I opened the OMEdit GUI and it asked me something about 3.2.3 vs 4.0.0. I said 3.2.3, the default. The GUI partially seemed to work. I can open the OMEdit GUI, but none of the usual standard libaray is present. It threw an error like 
`[3] 16:39:51 Scripting Error
Failed to load package ModelicaReference (default) using MODELICAPATH /usr/bin/../lib/omlibrary:/home/rwhite/.openmodelica/libraries/.`

I don't think that's related to this, so I'll move on. 

I attempted to install this tool. First I searched for the installation directory of OMSimulator, which seems to be /usr/lib/ on my install. 

I cloned this repo into /usr/lib, which failed at first due to permissions errors. I ran the clone command again with sudo and it worked. 

I went into /usr/lib/OMSysIdent/ and ran make -j8 (cos I have 8), and it failed again due to permissions. Did sudo again and it gave the output in [OMSysIdent1.txt](https://github.com/OpenModelica/OMSysIdent/files/7314690/OMSysIdent1.txt).

Did the mkdir build step, failed again on permissions, now I `sudo su` cos I'm bored of these now...

`/usr/lib/OMSysIdent/build/cmake ..` looks like it's failing on `CMAKE_HAVE_LIBC_PTHREAD` and `-- OMSimulator - NOT Found
-- Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) 
WARNING,Python library not found.`

The final step I tried, `/usr/lib/OMSysIdent/build/make -j8` fails on a missing `Types.h` and `OMSimulator.h`. See output from these commands in [OMSysIdent2.txt](https://github.com/OpenModelica/OMSysIdent/files/7314731/OMSysIdent2.txt).

Can someone help with a more step-by-step set of installation instructions or let me know what I'm doing wrong? 

Thanks!
R

**Comment by casella** [comment]
You can manage open-source library installations with the package manager, see [instructions](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/packagemanager.html). We're planning to support this also from the OMEdit GUI in the next release.

**Comment by robot-army** [comment]
> You can manage open-source library installations with the package manager, see [instructions](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/packagemanager.html). We're planning to support this also from the OMEdit GUI in the next release.

Thanks much, I'll try that when I'm back at the office. Do you think that'll help with OMSysIdent though? I feel like they might not be related, but if you think they might be I'll give that another shot.

**Comment by casella** [comment]
@adrpo, can you please help with this?

**Comment by bernhard-thiele** [comment]
The steps given in the [README.md](https://github.com/OpenModelica/OMSysIdent) don't require an OpenModelica installation, but require that the OMSimulator project is cloned (and built) and shares the same parent directory with OMSimulator, e.g.,

```
repos/OMSimulator
repos/OMSysIdent
```

However, the OMSimulator Python module structure changed and it didn't work anymore. This should be fixed by 54030bf.

The dependency to OMSimulator is not handled in a good way and breaks easily if something changes in OMSimulator. This was experienced in #5 (I just discovered that issue). But contrary to the description in #5 I've not seen a problem with OMTLMSimulator, possibly that part already got fixed in the OMSimulator repo.

**Comment by robot-army** [comment]
Excellent, I've just tried again, following these instructions, and got MUCH further. Now, when I try to run the python example I get: 

`rwhite@rwhite-virtual-machine:~/Desktop/OMSysIdent/testsuite/python$ python3 HelloWorld_cs_Fit.py 
Traceback (most recent call last):
  File "/home/rwhite/Desktop/OMSysIdent/testsuite/python/HelloWorld_cs_Fit.py", line 9, in <module>
    from OMSysIdent import OMSysIdent
ModuleNotFoundError: No module named 'OMSysIdent'
`

**Comment by robot-army** [comment]
OK, so I've tried again, from the top on a new install and I'm still having the error above. 

I think there's a final step I'm missing to get the OMSysIdent into my...python...stuff...somehow. 

I also had a similar error with OMSimulator, but a `pip install OMSimulator` seemed to fix that.

**Comment by robot-army** [comment]
[installlog.txt](https://github.com/OpenModelica/OMSysIdent/files/10928435/installlog.txt)


Here's a *very* verbose log of the install...from figuring out that OMSimulator has dependencies and that I should install them, right up to the OMSysIdent module not working.
